kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hawtio-operator
subjects:
- kind: ServiceAccount
  name: hawtio-operator
  namespace: {{NAMESPACE}}
roleRef:
  kind: ClusterRole
  name: hawtio-operator
  apiGroup: rbac.authorization.k8s.io
