apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../deploy/crd
- ../deploy/crs
- ../deploy
- scorecard

patches:
- path: patches/patch-watch-namespaces.yaml
  target:
    group: apps
    kind: Deployment
    name: hawtio-operator
    version: v1
