# Used for testing only
about:
  title: Hawtio Console
  additionalInfo: The Hawtio console eases the discovery and management of hawtio-enabled
    applications deployed on OpenShift.
branding:
  appName: Hawtio Console
  appLogoUrl: img/hawtio-logo.svg
online:
  consoleLink:
    text: Hawtio Console
    section: Hawtio
    imageRelativePath: /online/img/favicon.ico
