apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hawtio

resources:
- ../crd
- ../cluster_role.yaml
- ../cluster_role_binding.yaml
- ../role.yaml
- ../role_binding.yaml
- ../service_account.yaml
- role_app_user.yaml
